# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Draft release for Signum Node

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Phoenix Wallet
        run: |
          cd ./ci
          ./updatePhoenix.sh
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bundle OpenApi Doc
        run: |
          cd ./openapi
          npm ci
          npm run build
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build All
        run: ./gradlew release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Signum Node ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Get the version number
        id: get_version_number
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload Release Asset - Zip
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/distributions/signum-node.zip
          asset_name: signum-node-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset - Zip checksum
        id: upload-release-asset-zip-checksum
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/checksums/signum-node.zip.sha256
          asset_name: signum-node-${{ steps.get_version.outputs.VERSION }}.zip.sha256
          asset_content_type: text/plain

      - name: Upload Release Asset - WindowsZip
        id: upload-release-asset-windows-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/distributions/signum-node-win_x64.zip
          asset_name: signum-node-${{ steps.get_version.outputs.VERSION }}-win_x64.zip
          asset_content_type: application/zip
      - name: Upload Release Asset - WindowsZip checksum
        id: upload-release-asset-windows-zip-checksum
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/checksums/signum-node-win_x64.zip.sha256
          asset_name: signum-node-${{ steps.get_version.outputs.VERSION }}-win_x64.zip.sha256
          asset_content_type: text/plain
